version: '3.8'

services:
  email_app:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    container_name: email_app
    working_dir: /app
    command: sh -c "npm run start:dev"
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
      - mysqldb
    volumes:
      - .:/app

  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ""
      MONGO_INITDB_ROOT_PASSWORD: ""
    volumes:
      - mongodb_data:/data/db

  mysqldb:
    image: mysql
    container_name: mysqldb
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      environment:
      # MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_DATABASE: email
    ports:
      - "3306:3306"
    volumes:
      - mysqldb_data:/var/lib/mysql

volumes:
  mongodb_data:
  mysqldb_data: